title: Stakeholder Therapy
description: No bullshit. Occasionally hopeful.
url: "https://stakeholdertherapy.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - migrate_wp_to_jekyll.py
  - .git
  - .gitignore

# Include headers file
include:
  - _headers

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
