title: Stakeholder Therapy
description: No bullshit. Occasionally hopeful.
url: "https://stakeholdertherapy.com"
baseurl: ""

# Author
author:
  name: Daniel Bernal
  url: https://danielbernal.co

# Social
twitter:
  username: afterxleep
  card: summary_large_image

social:
  name: Daniel Bernal
  links:
    - https://twitter.com/afterxleep
    - https://github.com/afterxleep

# SEO
lang: en_US

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - migrate_wp_to_jekyll.py
  - .git
  - .gitignore

# Include headers file
include:
  - _headers
  - robots.txt

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
